{{- if .Values.backup.enabled }}
{{- $db_password := randAscii 20 }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    cronjob-type: backup
spec:
  schedule: {{ .Values.backup.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          shareProcessNamespace: true
          containers:
          - name: backup
            {{- include "drupal.php-container" . | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" . | nindent 14 }}
              - name: {{ .Release.Name }}-backup
                mountPath: /backups
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{ include "drupal.backup-command" . | nindent 16 }}
                {{ include "mariadb.db-validation" . | nindent 16 }}
            securityContext:
              capabilities:
                add:
                  - SYS_PTRACE
          - name: mariadb
            image: docker.io/bitnami/mariadb:10.2.32
            imagePullPolicy: IfNotPresent
            env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ $db_password }}
            - name: MARIADB_DATABASE
              value: drupal
            ports:
            - containerPort: 3306
              name: mariadb
            resources:
              {{- .Values.backup.resources | toYaml | nindent 14 }}
            securityContext:
              capabilities:
                add:
                  - SYS_PTRACE
          restartPolicy: Never
          volumes:
            {{- include "drupal.volumes" . | nindent 12 }}
            - name: {{ .Release.Name }}-backup
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-backup
          {{- include "drupal.imagePullSecrets" . | nindent 10 }}
{{- end }}

---
