{{- range $index, $job := .Values.php.cron }}
apiVersion: {{ include "drupal.cron.api-version" $ | trim }}
kind: CronJob
metadata:
  {{- $indexHash := sha256sum $index | trunc 3 }}
  {{- $nameAppendix := (gt (len $index) 6) | ternary ( print ($index | trunc 3) print $indexHash ) $index}}
  {{- $releaseNameTrimmed := substr 0 (int (sub 46 (len $nameAppendix))) $.Release.Name }}
  name: {{ $releaseNameTrimmed }}-cron-{{ $nameAppendix }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "drupal.release_labels" $ | nindent 12 }}
            cronjob: "true"
        spec:
          enableServiceLinks: false
          containers:
          - name: drupal-cron
            {{- include "drupal.php-container" $ | nindent 12 }}
            volumeMounts:
              {{- include "drupal.volumeMounts" $ | nindent 14 }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{- include "cron.entrypoints" $ | nindent 16 }}
                set -x
                if [ {{ include "drupal.installation-in-progress-test" $ }} ]; then
                  # Retry util install finishes.
                  exit 1
                fi

                # By default run a cron job in a very simple manner.
                if [ "{{ $job.stats }}" != "true" ]; then
                  {{ $job.command | nindent 18 }}
                  exit
                fi

                # Run the following code, if the silta.yml has "stat: true" in the cron command.

                # Disable debugging while setting up things.
                # Don't output the set command itself.
                { set +x ; } 2>/dev/null

                # We need to save the executable command(s) into a file,
                # because the 'time' can execute only command files,
                # not the shell constructs.
                script="/tmp/cron.$$"
                cat << CMD > "${script}"
                #!/bin/bash
                set -x
                {{ $job.command | nindent 16 }}
                CMD
                chmod 755 "${script}"

                # Try to make the temporary files more unique.
                # $$ = PID of the current running shell.
                stats="/tmp/stats.$$"
                output="/tmp/output.$$"
                output_json="/tmp/output_json.$$"

                # The execution of the actual cron command.
                # For backward compatibility reasons send the output to stdout as well (tee).
                /usr/bin/time -f '"duration_s":%e,"peak_mem_kb":%M' -o "${stats}" "${script}" 2>&1 \
                | tee "${output}"

                # It's tricky to get the exit code of a random command from a pipeline.
                # It is highly shell-dependent.
                exit_code="${PIPESTATUS[0]}"

                # Convert the command output to JSON.
                php -r 'print json_encode(file_get_contents("/dev/stdin"))."\n";' < "${output}" > "${output_json}"

                # If the error code is non-zero,
                # the output file contains also a warning,
                # which is not JSON.
                # Get rid of this.
                stats="$(grep -E '"duration_s".*"peak_mem_kb"' ${stats})"

                cron_name="{{ $index }}"

                # Assemble the JSON output.
                cat << JSON
                {"cron_name":"${cron_name}",${stats},"exit_code":${exit_code},"output":$(cat "${output_json}")}
                JSON

                # Use the exit code of the actual cron command.
                exit "$exit_code"

            resources:
              {{ if $job.resources }}
              {{- $job.resources | toYaml | nindent 14 }}
              {{ else }}
              {{- $.Values.php.resources | toYaml | nindent 14 }}
              {{- end }}
          restartPolicy: Never
          nodeSelector:
            {{ if $job.nodeSelector }}
            {{- $job.nodeSelector | toYaml | nindent 12 }}
            {{ else }}
            {{- $.Values.php.nodeSelector | toYaml | nindent 12 }}
            {{- end }}
          tolerations:
            {{ if $job.nodeSelector }}
            {{- include "drupal.tolerations" $job.nodeSelector | nindent 12 }}
            {{ else }}
            {{- include "drupal.tolerations" $.Values.php.nodeSelector | nindent 12 }}
            {{- end }}

          volumes:
            {{- include "drupal.volumes" $ | nindent 12 }}

          {{- include "drupal.imagePullSecrets" $ | nindent 10 }}
---
{{- end }}
