{{- if .Values.perconaXtraDB.enabled }}
apiVersion: pxc.percona.com/v1-9-0
kind: PerconaXtraDBCluster
metadata:
  name: {{ include "pxc-name" . }}
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  crVersion: 1.9.0
  secretsName: {{ .Release.Name }}-pxc
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: 8.0-recommended
    schedule: "0 4 * * *"
  pxc:
    labels:
      {{- include "drupal.release_labels" . | nindent 8 }}
    size: {{ .Values.perconaXtraDB.pxc.replicas }}
    image: percona/percona-xtradb-cluster:8.0.23-14.1
    autoRecovery: true
    configuration: |
      {{- .Values.perconaXtraDB.pxc.configuration | nindent 6 }}
    resources:
      {{- .Values.perconaXtraDB.pxc.resources | toYaml | nindent 6 }}
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: {{ .Values.perconaXtraDB.pxc.persistence.size }}
  haproxy:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:1.9.0-haproxy
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.9.0-logcollector
{{- end }}