{{- if .Values.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-varnish
  annotations:
    auto-downscale/down: "false"
    beta.cloud.google.com/backend-config: '{"ports": {"80":"{{ .Release.Name }}-drupal"}}'
    {{- if .Values.cluster }}
    {{- if .Values.cluster.vpcNative }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky-proxy"
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
  - name: admin
    port: 6082 
  selector:
    {{- include "drupal.release_selector_labels" . | nindent 4 }}
    service: varnish
{{- end }}
